# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'google-examples-swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for google-examples-swift
  pod 'Firebase/Core'
  pod 'FirebaseAnalytics'
  pod 'GoogleSignIn'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'GTMOAuth2'
  pod 'GoogleAPIClientForREST/Drive'
  pod 'GoogleAPIClientForREST/Sheets'
  pod 'GoogleAPIClientForREST/Calendar'
  pod 'GoogleAPIClientForREST/YouTube'


  target 'google-examples-swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'google-examples-swiftUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
